name: C/C++ CI

on:
  push:
    branches: [ "openwrt-18.06-mod-dw33d" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install pkg
      run: sudo apt update && sudo apt install build-essential gawk flex git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev -y
    - name: Update & Install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
    - uses: actions/cache@v3
      with:
        path: |
          build_dir/host*
          build_dir/toolchain*
        key: ${{ runner.os }}-1806
    - name: make
      run: make world $(($(nproc)+1)) BUILD_LOG=1
    - name: pack
      run: tar caf bin.txz bin
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: bin.txz
