name: mybuild

on:
  workflow_dispatch:
  push:
    branches: [ "openwrt-21.02-mod-dw33d" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=UserBuild_$(git log -1 --format='%h')" >> $GITHUB_OUTPUT
    - name: install pkg
      run: sudo apt update && sudo apt install build-essential gawk flex git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev -y
    - name: Update & Install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -f curl
        ./scripts/feeds install -f libcurl
        make defconfig
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          build_dir/host*
          build_dir/toolchain*
          staging_dir/toolchain*
          staging_dir/host*
        key: ${{ runner.os }}-2102
    - name: Cache timestape
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        find build_dir/{host*,toolchain-*} -name .built\* -exec touch {} \;
        touch staging_dir/{host*,toolchain-*}/stamp/.*
    - name: make
      run: make world -j$(nproc) BUILD_LOG=1
    - name: pack
      run: | 
        tar caf kmods.txz -C bin/targets/ath79/nand/packages/ .
        tar caf packages.txz -C bin/packages/ . || true
    - name: upload image builder
      uses: actions/upload-artifact@v3
      with:
        name: imagebuilder
        path: bin/**/*builder*
    - name: upload packages
      uses: actions/upload-artifact@v3
      with:
        name: kmods
        path: kmods.txz
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          bin/**/*builder*
          kmods.txz
          packages.txz

